# Generated by Django 5.2.8 on 2025-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendiz',
            name='id',
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
