# Generated by Django 5.2.8 on 2025-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_remove_aprendiz_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
