# Generated by Django 5.2.8 on 2025-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
