# Generated by Django 5.2.8 on 2025-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel_formacion', models.CharField(choices=[('Aux', 'Auxiliar'), ('OPE', 'Operario'), ('TEC', 'Técnico'), ('TEG', 'Tecnólogo'), ('ESP', 'Especialización Tecnológica'), ('COM', 'Complementario')], max_length=3)),
                ('modalidad', models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('MIX', 'Mixta')], default='PRE', max_length=3)),
                ('duracion_meses', models.PositiveIntegerField()),
                ('duracion_horas', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('competencias', models.TextField()),
                ('perfil_egreso', models.TextField()),
                ('requisitos_ingreso', models.TextField()),
                ('centro_formacion', models.CharField(max_length=200)),
                ('regional', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('DIS', 'Suspendido'), ('CAN', 'Cancelado')], default='ACT', max_length=3)),
                ('fecha_creacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
