# Generated by Django 5.2.8 on 2025-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], default='CC', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('nivel_educativo', models.CharField(choices=[('TEC', 'Tecnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], default='MAE', max_length=3)),
                ('especialidad', models.CharField(max_length=100)),
                ('años_experiencia', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='programa',
        ),
    ]
